import streamlit as st

st.set_page_config(page_title="Terms of Service — StructOptima", layout="wide")

st.title("Terms of Service")
st.caption("Last updated: March 2026")

st.markdown("""
## 1. Service Description

StructOptima provides **preliminary structural analysis** for educational and pre-design purposes. 
The platform generates automated structural designs compliant with Indian Standard codes 
(IS 456:2000, IS 1893:2016, IS 13920:2016, IS 875) based on user-provided inputs.

## 2. Professional Verification Requirement

All outputs generated by StructOptima **must be independently verified by a licensed Structural 
Engineer** before any construction use. By using this tool, you agree that:

- Outputs are **not substitutes** for professional engineering judgment
- The tool uses simplified analysis methods and may not account for all loading conditions
- Site-specific factors, geotechnical conditions, and local building code variations require independent assessment

## 3. Payment Terms

- Report downloads are charged on a **pay-per-report** basis
- **No refunds** on reports once downloaded
- All payments are processed securely via Razorpay
- Prices are displayed in Indian Rupees (INR) and include applicable taxes

## 4. Data Policy

- Structural data and drawings entered by users are **not stored beyond the browser session**
- No user design data is retained on our servers after the session ends
- Payment information is handled exclusively by Razorpay's secure payment gateway

## 5. Limitation of Liability

StructOptima, its developers, and operators provide the service **"as-is"** without warranties 
of any kind. We are not liable for any damages, losses, or injuries arising from the use of 
designs produced by this tool.

## 6. Acceptance

By using StructOptima, you acknowledge that you have read, understood, and agree to these Terms of Service.

---

*For questions, contact: srinidh.ameerpeta@gmail.com*
""")
